name: CI
on: [push, pull_request]

env:
  CI: "ON"
  HOMEBREW_NO_ANALYTICS: "ON"
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"

jobs:        
  mac-serial-build:
    name: macOS Serial Build
    runs-on: macos-latest
    strategy:
      matrix:
        version: [13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install GCC
        run: |
          brew install gcc@${{ matrix.version }} openblas pkg-config
          ln -s /usr/local/bin/gfortran-${{ matrix.version }} /usr/local/bin/gfortran
          ln -s /usr/local/bin/gcc-${{ matrix.version }} /usr/local/bin/gcc
          ln -s /usr/local/bin/g++-${{ matrix.version }} /usr/local/bin/g++
          echo "PKG_CONFIG_PATH=/usr/local/opt/openblas/lib/pkgconfig" >> $GITHUB_ENV

      - name: Install cmake
        run: pip3 install cmake

      # Currently not required, but will be if I implement NB analysis
      # - name: Install Python Packages
      #   run: |
      #     python -m pip install --upgrade pip setuptools wheel
      #     # Install from requirements as there is not a python project present
      #     pip install -r requirements.txt

      - name: Set Compiler
        run: |
          echo "FC=gfortran-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV

      - name: Configure project in serial
        run: cmake --fresh -B cmake-build-debug -DCMAKE_BUILD_TYPE=Debug -DMPI=Off
        
      - name: Build project
        run: cmake --build cmake-build-debug

      - name: Run ctest
        run: ctest --test-dir ./cmake-build-debug --output-on-failure
